AllCops:
  Exclude:
    - 'db/schema.rb'

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
